# -*- coding: utf-8 -*-
"""bubble sort.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M1_-KVLiYi4zvH9BgwKsI5ln_EcDoUll
"""

def bubble_sort(arr):
    n = len(arr)
    for i in range(n):
        for j in range(0, n - i - 1):
            if arr[j] > arr[j + 1]:
                arr[j], arr[j + 1] = arr[j + 1], arr[j]
    return arr
print(bubble_sort([64, 34, 25, 12, 22, 11, 90]))