# -*- coding: utf-8 -*-
"""prime number .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UlvBZZ1bZhkKGA-liTOClk0WJA4GSayz
"""

def is_prime(num):
    """Check if a number is prime."""
    if num <= 1:
        return False
    for i in range(2, int(num ** 0.5) + 1):
        if num % i == 0:
            return False
    return True
number = 29
if is_prime(number):
    print(f"{number} is a prime number.")
else:
    print(f"{number} is not a prime number.")

