# -*- coding: utf-8 -*-
"""zero.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BFoRRXUSoDfXUHv3Jzns55SFlBEgdJ-N
"""

def move_zeros(nums):
    zero_count = nums.count(0)
    nums = [num for num in nums if num != 0]
    nums.extend([0] * zero_count)
    return nums

# Example
print(move_zeros([0, 1, 0, 3, 12]))